<a href="https://colab.research.google.com/github/mercyclaudiam-netizen/Dashboard_KimiaFarma/blob/main/Pre_Processing_PBI_Kimia_Farma_x_Rakamin.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import warnings
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline


print('numpy version : ',np.__version__)
print('pandas version : ',pd.__version__)
print('seaborn version : ',sns.__version__)

numpy version :  2.0.2
pandas version :  2.2.2
seaborn version :  0.13.2

# Data Pre-Processing

## Final Transaction Table

In [ ]:
df_ft = pd.read_csv('/content/kf_final_transaction.csv')
display(df_ft.head())

,transaction_id,date,branch_id,customer_name,product_id,price,discount_percentage,rating
0,TRX5844188,9/7/2023,88605,Elizabeth Thomas,KF260,118700,0.05,3.0
1,TRX6182886,11/7/2022,27840,Andrew Martinez,KF492,751900,0.07,4.8
2,TRX7691180,5/30/2023,62913,Charles Reynolds,KF540,744200,0.03,3.3
3,TRX3205743,11/28/2022,31604,Casey Cochran,KF389,761700,0.06,3.5
4,TRX3644533,5/28/2023,20322,Rebecca Moore,KF854,681000,0.13,4.1

In [ ]:
df_ft.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 672458 entries, 0 to 672457
Data columns (total 8 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   transaction_id       672458 non-null  object
 1   date                 672458 non-null  object
 2   branch_id            672458 non-null  int64
 3   customer_name        672458 non-null  object
 4   product_id           672458 non-null  object
 5   price                672458 non-null  int64
 6   discount_percentage  672458 non-null  float64
 7   rating               672458 non-null  float64
dtypes: float64(2), int64(2), object(4)
memory usage: 41.0+ MB

In [ ]:
df_ft.describe()

           branch_id          price  discount_percentage         rating
count  672458.000000  672458.000000        672458.000000  672458.000000
mean    54232.575093  516347.954519             0.074992       4.000033
std     26025.980201  284547.593398             0.043477       0.579164
min     11079.000000    2100.000000             0.000000       3.000000
25%     31016.000000  296900.000000             0.040000       3.500000
50%     53629.000000  523100.000000             0.070000       4.000000
75%     76442.000000  757900.000000             0.110000       4.500000
max     99997.000000  997500.000000             0.150000       5.000000

In [ ]:
df_ft.duplicated().sum()

np.int64(0)

In [ ]:
df_ft.isna().sum()

transaction_id         0
date                   0
branch_id              0
customer_name          0
product_id             0
price                  0
discount_percentage    0
rating                 0
dtype: int64

## Inventory Table

In [ ]:
df_i = pd.read_csv('/content/kf_inventory.csv')
display(df_i.head())

,Inventory_ID,branch_id,product_id,product_name,opname_stock
0,INV1162281,12369,KF240,"Psycholeptics drugs, Anxiolytic drugs",86
1,INV3776318,95982,KF190,"Psycholeptics drugs, Anxiolytic drugs",74
2,INV7296268,20322,KF751,"Other analgesics and antipyretics, Pyrazolones...",71
3,INV1114840,20242,KF881,"Other analgesics and antipyretics, Salicylic a...",10
4,INV9288151,75963,KF818,"Anti-inflammatory and antirheumatic products, ...",87

In [ ]:
df_i.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1035000 entries, 0 to 1034999
Data columns (total 5 columns):
 #   Column        Non-Null Count    Dtype
---  ------        --------------    -----
 0   Inventory_ID  1035000 non-null  object
 1   branch_id     1035000 non-null  int64
 2   product_id    1035000 non-null  object
 3   product_name  1035000 non-null  object
 4   opname_stock  1035000 non-null  int64
dtypes: int64(2), object(3)
memory usage: 39.5+ MB

In [ ]:
df_i.describe()

          branch_id  opname_stock
count  1.035000e+06  1.035000e+06
mean   5.422225e+04  4.999722e+01
std    2.602987e+04  2.916266e+01
min    1.107900e+04  0.000000e+00
25%    3.101600e+04  2.500000e+01
50%    5.362900e+04  5.000000e+01
75%    7.644200e+04  7.500000e+01
max    9.999700e+04  1.000000e+02

In [ ]:
df_i.isna().sum()

Inventory_ID    0
branch_id       0
product_id      0
product_name    0
opname_stock    0
dtype: int64

In [ ]:
df_i.duplicated().sum()

np.int64(0)

Kantor Cabang Table

In [ ]:
df_kc = pd.read_csv('/content/kf_kantor_cabang.csv')
display(df_kc.head())

,branch_id,branch_category,branch_name,kota,provinsi,rating
0,63116,Klinik-Apotek-Laboratorium,Kimia Farma - Klinik-Apotek-Laboratorium,Ciamis,Jawa Barat,4.7
1,31494,Klinik-Apotek-Laboratorium,Kimia Farma - Klinik-Apotek-Laboratorium,Gorontalo,Gorontalo,4.6
2,27840,Apotek,Kimia Farma - Apotek,Denpasar,Bali,4.3
3,44209,Klinik & Apotek,Kimia Farma - Klinik & Apotek,Cilacap,Jawa Tengah,4.5
4,73710,Apotek,Kimia Farma - Apotek,Probolinggo,Jawa Timur,4.0

In [ ]:
df_kc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1725 entries, 0 to 1724
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   branch_id        1725 non-null   int64
 1   branch_category  1725 non-null   object
 2   branch_name      1725 non-null   object
 3   kota             1725 non-null   object
 4   provinsi         1725 non-null   object
 5   rating           1725 non-null   float64
dtypes: float64(1), int64(1), object(4)
memory usage: 81.0+ KB

In [ ]:
df_kc.describe()

          branch_id       rating
count   1725.000000  1725.000000
mean   54209.667826     4.448232
std    26053.355162     0.323434
min    11079.000000     3.900000
25%    30970.000000     4.200000
50%    53629.000000     4.500000
75%    76442.000000     4.700000
max    99997.000000     5.000000

In [ ]:
df_kc.isna().sum()

branch_id          0
branch_category    0
branch_name        0
kota               0
provinsi           0
rating             0
dtype: int64

In [ ]:
df_kc.duplicated().sum()

np.int64(0)

Prodcut Table

In [ ]:
df_p = pd.read_csv('/content/kf_product.csv')
display(df_p.head())

,product_id,product_name,product_category,price
0,KF162,"Anti-inflammatory and antirheumatic products, ...",M01AE,840200
1,KF374,"Anti-inflammatory and antirheumatic products, ...",R03,867500
2,KF801,"Other analgesics and antipyretics, Salicylic a...",N05C,530300
3,KF519,"Other analgesics and antipyretics, Pyrazolones...",M01AE,626400
4,KF679,"Psycholeptics drugs, Anxiolytic drugs",M01AE,924800

In [ ]:
df_p.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   product_id        150 non-null    object
 1   product_name      150 non-null    object
 2   product_category  150 non-null    object
 3   price             150 non-null    int64
dtypes: int64(1), object(3)
memory usage: 4.8+ KB

In [ ]:
df_p.describe()

               price
count     150.000000
mean   517024.666667
std    285663.005791
min      2100.000000
25%    297875.000000
50%    526700.000000
75%    757800.000000
max    997500.000000

In [ ]:
df_p.isna().sum()

product_id          0
product_name        0
product_category    0
price               0
dtype: int64

In [ ]:
df_p.duplicated().sum()

np.int64(0)

In [ ]:
df_rs = pd.read_csv('/content/kf_result.csv')
display(df_rs.head())

,transaction_id,date,branch_id,branch_name,kota,provinsi,rating_cabang,customer_name,product_id,product_name,actual_price,discount_percentage,persentase_gross_laba,nett_sales,nett_profitt,rating_transaksi
0,TRX3248504,2020-01-01,92582,Kimia Farma - Apotek,Sibolga,Sumatera Utara,4.4,Susan Stevens DDS,KF162,"Anti-inflammatory and antirheumatic products, ...",840200,0.01,0.30,831798,249539.40,3.0
1,TRX9756282,2020-01-01,43663,Kimia Farma - Klinik-Apotek-Laboratorium,Ambon,Maluku,4.0,Jeffrey Lutz,KF162,"Anti-inflammatory and antirheumatic products, ...",840200,0.00,0.30,840200,252060.00,3.0
2,TRX2604879,2020-01-01,48243,Kimia Farma - Klinik & Apotek,Tasikmalaya,Jawa Barat,4.1,Jay Mitchell,KF223,"Anti-inflammatory and antirheumatic products, ...",401700,0.15,0.25,341445,85361.25,3.0
3,TRX2861898,2020-01-01,12174,Kimia Farma - Apotek,Pangkalpinang,Bangka Belitung,4.7,Amanda Braun,KF395,Drugs for obstructive airway diseases,755400,0.09,0.30,687414,206224.20,3.0
4,TRX9941602,2020-01-01,69958,Kimia Farma - Klinik & Apotek,Palembang,Sumatera Selatan,4.7,Tracy King,KF402,"Other analgesics and antipyretics, Salicylic a...",906500,0.12,0.30,797720,239316.00,3.0

In [ ]:
df_rs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 672458 entries, 0 to 672457
Data columns (total 16 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   transaction_id         672458 non-null  object
 1   date                   672458 non-null  object
 2   branch_id              672458 non-null  int64
 3   branch_name            672458 non-null  object
 4   kota                   672458 non-null  object
 5   provinsi               672458 non-null  object
 6   rating_cabang          672458 non-null  float64
 7   customer_name          672458 non-null  object
 8   product_id             672458 non-null  object
 9   product_name           672458 non-null  object
 10  actual_price           672458 non-null  int64
 11  discount_percentage    672458 non-null  float64
 12  persentase_gross_laba  672458 non-null  float64
 13  nett_sales             672458 non-null  int64
 14  nett_profitt           672458 non-null  float64
 15  rating_transaksi       672458 non-null  float64
dtypes: float64(5), int64(3), object(8)
memory usage: 82.1+ MB

In [ ]:
df_rs.isna().sum()

transaction_id           0
date                     0
branch_id                0
branch_name              0
kota                     0
provinsi                 0
rating_cabang            0
customer_name            0
product_id               0
product_name             0
actual_price             0
discount_percentage      0
persentase_gross_laba    0
nett_sales               0
nett_profitt             0
rating_transaksi         0
dtype: int64

In [ ]:
df_rs.duplicated().sum()

np.int64(0)

In [ ]:
df_rs.describe()

,branch_id,rating_cabang,actual_price,discount_percentage,persentase_gross_laba,nett_sales,nett_profitt,rating_transaksi
count,672458.000000,672458.000000,672458.000000,672458.000000,672458.000000,672458.000000,672458.000000,672458.000000
mean,54232.575093,4.447984,516347.954519,0.074992,0.256225,477607.806464,135644.141433,4.000033
std,26025.980201,0.323350,284547.593398,0.043477,0.056106,264422.423296,85148.115522,0.579164
min,11079.000000,3.900000,2100.000000,0.000000,0.100000,1785.000000,178.500000,3.000000
25%,31016.000000,4.200000,296900.000000,0.040000,0.200000,273702.000000,56411.000000,3.500000
50%,53629.000000,4.500000,523100.000000,0.070000,0.300000,480150.000000,142444.500000,4.000000
75%,76442.000000,4.700000,757900.000000,0.110000,0.300000,703380.000000,211014.000000,4.500000
max,99997.000000,5.000000,997500.000000,0.150000,0.300000,997500.000000,299250.000000,5.000000